package vista;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JDesktopPane;


/**
 *
 * @author Victor
 */
public class FrmMenu extends javax.swing.JFrame {
    public static JDesktopPane jDesktopPane_menu;
    private Color defaultButtonColor;
    //private Color selectedButtonColor = new Color(173, 216, 230); // Azul claro
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1320,700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema De Registro Administrador");
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0,0,ancho, (alto - 110));
        this.add(jDesktopPane_menu);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        User = new javax.swing.JMenu();
        Habitacion = new javax.swing.JMenu();
        Reservacion = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenu();
        Servicio = new javax.swing.JMenu();
        Factura = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        CerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User.setBackground(new java.awt.Color(153, 204, 255));
        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        User.setText("Usuarios");
        User.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        User.setPreferredSize(new java.awt.Dimension(150, 50));
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        jMenuBar1.add(User);

        Habitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        Habitacion.setText("Habitaciones");
        Habitacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Habitacion.setPreferredSize(new java.awt.Dimension(150, 50));
        Habitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HabitacionMouseClicked(evt);
            }
        });
        Habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitacionActionPerformed(evt);
            }
        });
        jMenuBar1.add(Habitacion);

        Reservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        Reservacion.setText("Reservaciones");
        Reservacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Reservacion.setPreferredSize(new java.awt.Dimension(150, 50));
        Reservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservacionMouseClicked(evt);
            }
        });
        Reservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservacionActionPerformed(evt);
            }
        });
        jMenuBar1.add(Reservacion);

        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        Cliente.setText("Clientes");
        Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Cliente.setPreferredSize(new java.awt.Dimension(150, 50));
        Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(Cliente);

        Servicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        Servicio.setText("Servicios");
        Servicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Servicio.setPreferredSize(new java.awt.Dimension(150, 50));
        Servicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(Servicio);

        Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        Factura.setText("Factura");
        Factura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Factura.setPreferredSize(new java.awt.Dimension(150, 50));
        Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Factura);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu6.setText("Cerrar Sesion");
        jMenu6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        jMenu6.add(CerrarSesion);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        FrmLogin login = new FrmLogin();
                    login.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        InterUser interUsuarioTab = new InterUser(); 
        abrirInternalFrame(interUsuarioTab);
        resaltarMenu(User);
    }//GEN-LAST:event_UserMouseClicked

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        //updateButtonColors(User);
    }//GEN-LAST:event_UserActionPerformed

    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        resaltarMenu(User);
    }//GEN-LAST:event_CerrarSesionMouseClicked

    private void HabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitacionActionPerformed
        
    }//GEN-LAST:event_HabitacionActionPerformed

    private void HabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HabitacionMouseClicked
        InterHabitaciones interHabitaciones = new InterHabitaciones(); 
        abrirInternalFrame(interHabitaciones); 
        resaltarMenu(User);
        //updateButtonColors(btn_users);
    }//GEN-LAST:event_HabitacionMouseClicked

    private void ReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservacionActionPerformed
        
    }//GEN-LAST:event_ReservacionActionPerformed

    private void ReservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservacionMouseClicked
        InterReservaciones interReservaciones = new InterReservaciones(); 
        abrirInternalFrame(interReservaciones); 
        resaltarMenu(User);
        //updateButtonColors(btn_users);
    }//GEN-LAST:event_ReservacionMouseClicked

    private void ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteMouseClicked
        InterClientes interClientes = new InterClientes(); 
        abrirInternalFrame(interClientes);
        resaltarMenu(User);
        //updateButtonColors(btn_users);
    }//GEN-LAST:event_ClienteMouseClicked

    private void ServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicioMouseClicked
        InterServicios interFacturas = new InterServicios(); 
        abrirInternalFrame(interFacturas); 
        resaltarMenu(User);
        //updateButtonColors(btn_users);
    }//GEN-LAST:event_ServicioMouseClicked

    private void FacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseClicked
        InterFactura interFactura = new InterFactura(); 
        abrirInternalFrame(interFactura); 
        resaltarMenu(User);
       // updateButtonColors(btn_users);
    }//GEN-LAST:event_FacturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CerrarSesion;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenu Factura;
    private javax.swing.JMenu Habitacion;
    private javax.swing.JMenu Reservacion;
    private javax.swing.JMenu Servicio;
    private javax.swing.JMenu User;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private void abrirInternalFrame(javax.swing.JInternalFrame frame) {
        // Cerrar todos los JInternalFrame abiertos
        jDesktopPane_menu.removeAll();
        jDesktopPane_menu.repaint();

        // Agregar el nuevo JInternalFrame
        jDesktopPane_menu.add(frame);
        frame.setVisible(true);
    }

    private void resaltarMenu(javax.swing.JMenu clickedMenu) {
    // Definir el color predeterminado para los menús
    java.awt.Color defaultColor = new java.awt.Color(240, 240, 240); // Color predeterminado (gris claro)
    java.awt.Color selectedColor = new java.awt.Color(100, 149, 237); // Color azul claro para el seleccionado

    // Restablecer el color de todos los menús
    User.setBackground(defaultColor);
    Habitacion.setBackground(defaultColor);
    Reservacion.setBackground(defaultColor);
    Cliente.setBackground(defaultColor);
    Servicio.setBackground(defaultColor);
    jMenu6.setBackground(defaultColor);

    // Cambiar el color del menú que fue clicado
    clickedMenu.setBackground(selectedColor);
}

/*private void updateButtonColors(javax.swing.JButton selectedButton) {
    // Restaurar todos los botones al color por defecto
    User.setBackground(defaultButtonColor);
    Habitacion.setBackground(defaultButtonColor);
    btn_books.setBackground(defaultButtonColor);
    Habitacion.setBackground(defaultButtonColor);

    // Establecer el color seleccionado en el botón activo
    selectedButton.setBackground(selectedButtonColor);
}*/
}
