package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
/**
 *
 * @author Victor
 */
public class FrmRecepcionista extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_Recepcionista;

    /**
     * Creates new form FrmRecepcionista
     */
    public FrmRecepcionista() {
        initComponents();
        this.setSize(new Dimension(1050, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema De Registro Recepcionista");

        this.setLayout(null);
        jDesktopPane_Recepcionista = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        jDesktopPane_Recepcionista.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_Recepcionista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Reservacion = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenu();
        Cobro = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuBar1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        Reservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        Reservacion.setText("Reservacion");
        Reservacion.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        Reservacion.setPreferredSize(new java.awt.Dimension(150, 50));
        Reservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservacionMouseClicked(evt);
            }
        });
        jMenuBar1.add(Reservacion);

        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        Cliente.setText("Cliente");
        Cliente.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        Cliente.setPreferredSize(new java.awt.Dimension(150, 50));
        Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(Cliente);

        Cobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        Cobro.setText("Cobro");
        Cobro.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        Cobro.setPreferredSize(new java.awt.Dimension(150, 50));
        Cobro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CobroMouseClicked(evt);
            }
        });
        jMenuBar1.add(Cobro);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu6.setText("Cerrar sesion");
        jMenu6.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cerrar sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservacionMouseClicked
        InterReservaciones interReservaciones = new InterReservaciones(); 
        abrirInternalFrame(interReservaciones); 
    }//GEN-LAST:event_ReservacionMouseClicked

    private void ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteMouseClicked
        InterClientes interClientes = new InterClientes(); 
        abrirInternalFrame(interClientes);
    }//GEN-LAST:event_ClienteMouseClicked

    private void CobroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CobroMouseClicked
        InterServicios interFacturas = new InterServicios(); 
        abrirInternalFrame(interFacturas); 
    }//GEN-LAST:event_CobroMouseClicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    FrmLogin login = new FrmLogin();
                    login.setVisible(true);
                    this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenu Cobro;
    private javax.swing.JMenu Reservacion;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
    private void abrirInternalFrame(javax.swing.JInternalFrame frame) {
        jDesktopPane_Recepcionista.removeAll();
        jDesktopPane_Recepcionista.repaint();
        
        jDesktopPane_Recepcionista.add(frame);
        frame.setVisible(true);
    }

}
