package vista;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.UIManager;
/**
 *
 * @author Victor
 */
public class FrmRecepcionista extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_Recepcionista;

    /**
     * Creates new form FrmRecepcionista
     */
    public FrmRecepcionista() {
        initComponents();
        this.setSize(new Dimension(1050, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema De Registro Recepcionista");

        this.setLayout(null);
        jDesktopPane_Recepcionista = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        jDesktopPane_Recepcionista.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_Recepcionista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Cliente = new javax.swing.JMenu();
        Reservacion = new javax.swing.JMenu();
        Servicios = new javax.swing.JMenu();
        Factura = new javax.swing.JMenu();
        Cerrar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuBar1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        Cliente.setForeground(new java.awt.Color(255, 102, 0));
        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        Cliente.setText("Cliente");
        Cliente.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        Cliente.setPreferredSize(new java.awt.Dimension(150, 50));
        Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(Cliente);

        Reservacion.setForeground(new java.awt.Color(255, 102, 0));
        Reservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        Reservacion.setText("Reservacion");
        Reservacion.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        Reservacion.setPreferredSize(new java.awt.Dimension(150, 50));
        Reservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservacionMouseClicked(evt);
            }
        });
        jMenuBar1.add(Reservacion);

        Servicios.setForeground(new java.awt.Color(255, 102, 0));
        Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        Servicios.setText("Servicios");
        Servicios.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        Servicios.setPreferredSize(new java.awt.Dimension(150, 50));
        Servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServiciosMouseClicked(evt);
            }
        });
        jMenuBar1.add(Servicios);

        Factura.setForeground(new java.awt.Color(255, 102, 0));
        Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        Factura.setText("Factura");
        Factura.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        Factura.setPreferredSize(new java.awt.Dimension(150, 50));
        Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Factura);

        Cerrar.setForeground(new java.awt.Color(255, 102, 0));
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        Cerrar.setText("Cerrar sesion");
        Cerrar.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        Cerrar.setPreferredSize(new java.awt.Dimension(150, 50));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cerrar sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Cerrar.add(jMenuItem1);

        jMenuBar1.add(Cerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservacionMouseClicked
        InterReservaciones interReservaciones = new InterReservaciones(); 
        abrirInternalFrame(interReservaciones); 
        cambiarColoresJMenu(Reservacion);
    }//GEN-LAST:event_ReservacionMouseClicked

    private void ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteMouseClicked
        InterClientes interClientes = new InterClientes(); 
        abrirInternalFrame(interClientes);
        cambiarColoresJMenu(Cliente);
    }//GEN-LAST:event_ClienteMouseClicked

    private void ServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiciosMouseClicked
        InterServicios interFacturas = new InterServicios(); 
        abrirInternalFrame(interFacturas);
        cambiarColoresJMenu(Servicios);
    }//GEN-LAST:event_ServiciosMouseClicked

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_CerrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    FrmLogin login = new FrmLogin();
                    login.setVisible(true);
                    this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void FacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseClicked
        // TODO add your handling code here:
        InterFactura interFactura = new InterFactura(); 
        abrirInternalFrame(interFactura);
        cambiarColoresJMenu(Factura);
    }//GEN-LAST:event_FacturaMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        // TODO add your handling code here:
        
        cambiarColoresJMenu(Cerrar);
    }//GEN-LAST:event_CerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cerrar;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenu Factura;
    private javax.swing.JMenu Reservacion;
    private javax.swing.JMenu Servicios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
    private void abrirInternalFrame(javax.swing.JInternalFrame frame) {
        jDesktopPane_Recepcionista.removeAll();
        jDesktopPane_Recepcionista.repaint();
        
        jDesktopPane_Recepcionista.add(frame);
        frame.setVisible(true);
    }
    private void cambiarColoresJMenu(javax.swing.JMenu menuSeleccionado) {
        // Colores
        Color colorSeleccionado = new Color(64, 64, 64); // Gris oscuro
        Color colorPredeterminado = UIManager.getColor("Menu.background"); // Color predeterminado del menú

        // Lista de menús
        javax.swing.JMenu[] menus = {Cliente, Factura, Reservacion, Servicios, Cerrar};

        for (javax.swing.JMenu menu : menus) {
            if (menu == menuSeleccionado) {
                menu.setBackground(colorSeleccionado);
                menu.setOpaque(true); // Asegurarse de que se aplique el color
            } else {
                menu.setBackground(colorPredeterminado);
                menu.setOpaque(false); // Volver al estilo predeterminado
            }
        }
    }
}
